### ISSUE TITLE
Trouble Running on Fresh Ubuntu 20.04 / V3.4.0

### ISSUE THREAD

**Issue by pfeiffee** [noonchen/STDF-Viewer#112]
For Version 3.4.0:
With a fresh install of Ubuntu 20.04 I get the following error at launch:
```
Traceback (most recent call last):
  File "STDF-Viewer.py", line 69, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "matplotlib/__init__.py", line 109, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "matplotlib/rcsetup.py", line 27, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "matplotlib/colors.py", line 51, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 476, in exec_module
  File "PIL/Image.py", line 132, in <module>
ImportError: libjpeg-dffd3595.so.62.3.0: cannot open shared object file: No such file or directory
[7] Failed to execute script 'STDF-Viewer' due to unhandled exception!
```

What dependencies are required to run this program? I can't find anything about what package includes libjpeg-dffd3595 other than the PIL libs in an unrelated project.

**Comment by noonchen** [comment]
Sorry for the late response, I added a cleanup step in the github action and apparently it deletes some required dependencies.

As for your issue, reinstall python package `pillow` might help? I am not sure though

**Comment by noonchen** [comment]
Hi, it should be fixing in the latest version, can you help me try test it?

**Comment by noonchen** [comment]
Assuming it is resolved, if not, please reopen it
